# Generated by Django 4.0 on 2023-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_desc',
            field=models.TextField(),
        ),
    ]
